"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import typing

from .helloworld_pb2 import *
class GreeterStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    def SayHello(self,
        request: global___HelloRequest,
    ) -> global___HelloReply: ...

    def SayRepeatHello(self,
        request: global___RepeatHelloRequest,
    ) -> typing.Iterator[global___HelloReply]: ...


class GreeterServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def SayHello(self,
        request: global___HelloRequest,
        context: grpc.ServicerContext,
    ) -> global___HelloReply: ...

    @abc.abstractmethod
    def SayRepeatHello(self,
        request: global___RepeatHelloRequest,
        context: grpc.ServicerContext,
    ) -> typing.Iterator[global___HelloReply]: ...


def add_GreeterServicer_to_server(servicer: GreeterServicer, server: grpc.Server) -> None: ...
